# SponsorFlow Nexus - Configuración
CONFIG_URL=https://raw.githubusercontent.com/yurislay9-ui/nexus-backend/refs/heads/main/config.json

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35,34

# Memoria aumentada para compilación (Compose + Hilt + KSP + Room + JNI)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Optimizaciones de Gradle
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true

org.gradle.daemon.performance.disable-logging=true