# SponsorFlow Nexus - Configuración
CONFIG_URL=https://raw.githubusercontent.com/yurislay9-ui/nexus-backend/refs/heads/main/config.json

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35,34

# Memoria aumentada para compilación
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon.performance.disable-logging=true